version: 2.1

jobs:
  build_and_test_linux-x86_64:
    docker:
      - image: cimg/rust:1.49
    steps:
      - checkout
      - run: cargo test
      - run: cd test_deps_if && cargo test

workflows:
  linux-x86_64:
    jobs:
      - build_and_test_linux-x86_64
